name: jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    jobs:
      build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Install dependacies
          run: cd frontend && npm ci

        - name: Run Jest tests
          run: cd frontend && npm test


